import Head from "next/head";
import { useState } from "react";

const skills = { Frontend: ["React", "Next.js", "TypeScript", "Tailwind CSS"], Backend: ["Node.js", "Express", "REST APIs"], Database: ["MongoDB", "PostgreSQL", "Prisma"], Tools: ["Git", "GitHub", "Vercel"] };
const projects = [
  { title: "Rental Management System", text: "Role-based access, booking workflows, inventory, and optimized database design.", tags: ["Next.js", "Node.js"], kind: "next" },
  { title: "Full Stack E-Commerce Platform", text: "A secure commerce flow with catalog, cart, orders, authentication, and cloud storage.", tags: ["React", "Node.js"], kind: "react" },
  { title: "Weather Application", text: "A responsive dashboard using live APIs with fast search and clean UX.", tags: ["React", "APIs"], kind: "api" },
];

export default function Home() {
  const [light, setLight] = useState(false);
  const [filter, setFilter] = useState("all");
  const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" });
  const [status, setStatus] = useState("");
  const [sending, setSending] = useState(false);
  const theme = light ? "bg-slate-50 text-slate-900" : "bg-slate-950 text-slate-100";
  const panel = light ? "border-slate-200 bg-white/80" : "border-slate-800 bg-slate-900/70";
  const muted = light ? "text-slate-600" : "text-slate-400";
  const input = light ? "border-slate-200 bg-white" : "border-slate-700 bg-slate-950";

  async function sendMessage(event) {
    event.preventDefault();
    if (!form.name || !form.email || !form.message) return setStatus("Name, email, and message are required.");
    setSending(true); setStatus("Sending your message...");
    try {
      const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
      const data = await response.json();
      if (!response.ok || !data.success) throw new Error(data.message || "Message could not be sent.");
      setForm({ name: "", email: "", subject: "", message: "" }); setStatus("Message sent successfully.");
    } catch (error) { setStatus(error.message); } finally { setSending(false); }
  }

  return <div className={`min-h-screen ${theme}`}>
    <Head><title>Mahir Aziz | Portfolio</title><meta name="description" content="Mahir Aziz, software engineer and full stack developer." /></Head>
    <nav className={`sticky top-0 z-20 border-b backdrop-blur-xl ${light ? "border-slate-200 bg-white/80" : "border-slate-800 bg-slate-950/80"}`}>
      <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-6 py-5"><a href="#home" className="text-xl font-black">Mahir Aziz<span className="text-indigo-500">.</span></a><div className="hidden gap-6 text-sm md:flex">{["about", "skills", "experience", "projects", "contact"].map((id) => <a className={`${muted} hover:text-indigo-500`} href={`#${id}`} key={id}>{id[0].toUpperCase() + id.slice(1)}</a>)}</div><div className="flex gap-3"><button type="button" onClick={() => setLight(!light)} className={`rounded-full border px-4 py-2 text-sm ${panel}`}>{light ? "Dark" : "Light"}</button><a href="https://drive.google.com/file/d/1QiMruuUmu2Q65KgX0o-ffTlNn27leXkf/view?usp=sharing" target="_blank" rel="noreferrer" className="rounded-full bg-indigo-600 px-4 py-2 text-sm font-bold text-white">Resume</a></div></div>
    </nav>
    <main id="home" className="mx-auto max-w-6xl px-6">
      <section className="grid min-h-[78vh] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mb-5 inline-block rounded-full border border-indigo-400/30 bg-indigo-500/10 px-4 py-2 text-sm font-semibold text-indigo-500">Open to software engineering opportunities</p><h1 className="text-6xl font-black tracking-tight sm:text-8xl">Mahir <span className="text-indigo-500">Aziz</span></h1><p className={`mt-6 text-xl ${muted}`}>Software Engineer | Full Stack Developer | Backend Developer</p><p className={`mt-3 ${muted}`}>Final Year B.Tech CSE Student at IIIT Bhopal · 400+ DSA Problems Solved</p><div className="mt-8 flex gap-3"><a href="#contact" className="rounded-full bg-indigo-600 px-6 py-3 font-bold text-white">Let&apos;s connect</a><a href="https://drive.google.com/file/d/1QiMruuUmu2Q65KgX0o-ffTlNn27leXkf/view?usp=sharing" target="_blank" rel="noreferrer" className={`rounded-full border px-6 py-3 font-bold ${panel}`}>View resume</a></div></div><div className="grid aspect-square max-w-md place-items-center rounded-[3rem] border border-indigo-400/30 bg-gradient-to-br from-indigo-500/30 to-cyan-400/20 shadow-2xl shadow-indigo-500/10 lg:ml-auto"><div className="grid h-64 w-64 place-items-center rounded-full border-8 border-indigo-500/50 bg-slate-900 text-6xl font-black text-indigo-300">&lt;/&gt;</div></div></section>
      <section id="about" className="py-16"><h2 className="mb-6 text-4xl font-black">About Me</h2><div className={`rounded-3xl border p-8 text-lg leading-8 ${panel}`}>Final Year Computer Science student at IIIT Bhopal with experience building scalable full-stack applications using React, Next.js, Node.js, Express.js, PostgreSQL, and TypeScript. I enjoy solving complex problems and building useful products.</div></section>
      <section id="skills" className="py-16"><h2 className="mb-8 text-4xl font-black">Skills</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(skills).map(([title, list]) => <div className={`rounded-3xl border p-6 ${panel}`} key={title}><h3 className="mb-5 text-xl font-bold text-indigo-500">{title}</h3><div className="flex flex-wrap gap-2">{list.map((skill) => <span className={`rounded-full px-3 py-1.5 text-sm ${light ? "bg-slate-100" : "bg-slate-800"}`} key={skill}>{skill}</span>)}</div></div>)}</div></section>
      <section id="experience" className="py-16"><h2 className="mb-8 text-4xl font-black">Experience</h2><div className={`rounded-3xl border p-8 ${panel}`}><div className="flex justify-between gap-4"><h3 className="text-2xl font-bold">Navrobotec</h3><span className={muted}>Oct 2025 - Dec 2025</span></div><p className="mt-2 font-semibold text-indigo-500">Full Stack Developer Intern</p><ul className={`mt-5 list-disc space-y-2 pl-5 ${muted}`}><li>Built backend modules and customer-order workflows.</li><li>Implemented inventory, product variants, and notification systems.</li><li>Improved database query performance.</li></ul></div></section>
      <section id="projects" className="py-16"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><h2 className="text-4xl font-black">Featured Projects</h2><div className="flex gap-2">{["all", "next", "react", "api"].map((item) => <button type="button" onClick={() => setFilter(item)} className={`rounded-full border px-4 py-2 text-sm font-semibold ${filter === item ? "border-indigo-500 bg-indigo-500 text-white" : panel}`} key={item}>{item.toUpperCase()}</button>)}</div></div><div className="grid gap-5 lg:grid-cols-3">{projects.filter((project) => filter === "all" || project.kind === filter).map((project) => <article className={`rounded-3xl border p-5 ${panel}`} key={project.title}><div className="mb-6 grid h-40 place-items-center rounded-2xl bg-gradient-to-br from-indigo-500/30 to-cyan-400/20 text-4xl font-black text-indigo-500">{project.kind.toUpperCase()}</div><h3 className="text-xl font-bold">{project.title}</h3><p className={`mt-3 leading-7 ${muted}`}>{project.text}</p><div className="mt-5 flex gap-2">{project.tags.map((tag) => <span className={`rounded-full px-3 py-1 text-xs ${light ? "bg-slate-100" : "bg-slate-800"}`} key={tag}>{tag}</span>)}</div></article>)}</div></section>
      <section className="grid gap-6 py-16 lg:grid-cols-2"><div><h2 className="mb-8 text-4xl font-black">Achievements</h2><div className="grid gap-4">{[["400+", "DSA problems solved"], ["8.29", "CGPA at IIIT Bhopal"], ["500+", "Students reached through events"]].map(([value, label]) => <div className={`flex items-center gap-5 rounded-3xl border p-5 ${panel}`} key={label}><strong className="text-3xl text-indigo-500">{value}</strong><span className={muted}>{label}</span></div>)}</div></div><div><h2 className="mb-8 text-4xl font-black">Leadership</h2><div className={`rounded-3xl border p-6 ${panel}`}><h3 className="text-xl font-bold text-indigo-500">Alumni Cell Outreach Lead</h3><p className={`mt-3 leading-7 ${muted}`}>Managed outreach initiatives and coordinated convocation events while building strong student and alumni connections.</p><h3 className="mt-6 text-xl font-bold text-indigo-500">Arunoday Club Executive</h3><p className={`mt-3 leading-7 ${muted}`}>Led community initiatives and social welfare activities.</p></div></div></section>
      <section id="contact" className="py-16"><h2 className="mb-8 text-4xl font-black">Let&apos;s connect</h2><div className={`rounded-3xl border p-8 ${panel}`}><p className={`mb-8 text-lg ${muted}`}>Let&apos;s build something impactful together.</p><form onSubmit={sendMessage} className="grid gap-5 md:grid-cols-2">{[["name", "Name"], ["email", "Email"], ["subject", "Subject (optional)"], ["message", "Your message"]].map(([key, label]) => key === "message" ? <textarea key={key} className={`min-h-36 rounded-2xl border px-4 py-3 outline-none focus:border-indigo-500 md:col-span-2 ${input}`} placeholder={label} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /> : <input key={key} className={`rounded-2xl border px-4 py-3 outline-none focus:border-indigo-500 ${key === "subject" ? "md:col-span-2" : ""} ${input}`} type={key === "email" ? "email" : "text"} placeholder={label} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />)}<div className="flex items-center gap-5 md:col-span-2"><button disabled={sending} className="rounded-full bg-indigo-600 px-6 py-3 font-bold text-white disabled:opacity-60" type="submit">{sending ? "Sending..." : "Send message"}</button>{status && <p className={status.includes("successfully") ? "text-emerald-500" : "text-rose-500"}>{status}</p>}</div></form></div></section>
    </main><footer className={`border-t px-6 py-8 text-center text-sm ${muted}`}>© 2026 Mahir Aziz · IIIT Bhopal</footer>
  </div>;
}
